"""
Abstract interface contracts for Rule Engine and individual Rules.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Dict, Any, List
from domain.models.calculation_context import CalculationContext


@dataclass(frozen=True)
class RuleResult:
    """
    Immutable result returned by an individual rule evaluation.

    Attributes:
        rule_id: Unique string identifier for the rule.
        category: Rule taxonomy category (e.g. 'classical', 'kp', 'nadi', 'jaimini', 'ai').
        rule_name: Display name of the rule.
        triggered: Boolean flag indicating if the rule condition matched.
        confidence_score: Confidence score float between 0.0 and 1.0.
        payload: Detailed dictionary payload generated by rule evaluation.
        rule_version: Version string of the rule.
    """
    rule_id: str
    category: str
    rule_name: str
    triggered: bool
    confidence_score: float
    payload: Dict[str, Any]
    rule_version: str


class IRule(ABC):
    """
    Abstract Base Class for modular rules evaluated by the RuleEngine.
    """

    @property
    @abstractmethod
    def rule_id(self) -> str:
        """Unique identifier string for the rule."""
        pass

    @property
    @abstractmethod
    def category(self) -> str:
        """Category string (e.g. 'classical', 'kp', 'nadi', 'jaimini')."""
        pass

    @abstractmethod
    def evaluate(self, context: CalculationContext) -> RuleResult:
        """
        Evaluates rule condition against the CalculationContext.

        Args:
            context: Immutable CalculationContext envelope.

        Returns:
            RuleResult entity.
        """
        pass


class IRuleEngine(ABC):
    """
    Abstract Base Class for Rule Engine dispatchers.
    """

    @abstractmethod
    def register_rule(self, rule: IRule) -> None:
        """Registers a new rule implementation."""
        pass

    @abstractmethod
    def evaluate_all(self, context: CalculationContext) -> List[RuleResult]:
        """Evaluates all registered rules against the CalculationContext."""
        pass
