"""
Abstract interface contracts for Rule Engine and individual Rules.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Dict, Any, List, Optional
from domain.models.calculation_context import CalculationContext


@dataclass(frozen=True)
class RuleResult:
    """
    Immutable result returned by an individual rule evaluation.

    Attributes:
        rule_id: Unique string identifier for the rule.
        category: Rule taxonomy category (e.g. 'classical', 'yoga', 'raja_yoga', 'dhana_yoga', 'arishta', 'neecha_bhanga', 'functional_dignity').
        rule_name: Display name of the rule.
        triggered: Boolean flag indicating if the rule condition matched.
        confidence_score: Confidence score float between 0.0 and 1.0.
        payload: Detailed dictionary payload generated by rule evaluation.
        rule_version: Version string of the rule.
        priority: Rule execution priority integer (higher = evaluated first).
    """
    rule_id: str
    category: str
    rule_name: str
    triggered: bool
    confidence_score: float
    payload: Dict[str, Any]
    rule_version: str
    priority: int = 100


class IRule(ABC):
    """
    Abstract Base Class for modular rules evaluated by the RuleEngine.
    Rules MUST read ONLY from CalculationContext and NEVER recalculate planets or houses.
    """

    @property
    @abstractmethod
    def rule_id(self) -> str:
        """Unique identifier string for the rule."""
        pass

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable display name of the rule."""
        pass

    @property
    @abstractmethod
    def version(self) -> str:
        """Rule version string."""
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """Detailed description of what the rule evaluates."""
        pass

    @property
    @abstractmethod
    def priority(self) -> int:
        """Execution priority integer (higher number = evaluated first)."""
        pass

    @property
    @abstractmethod
    def category(self) -> str:
        """Rule category string (e.g. 'classical', 'yoga', 'raja_yoga', 'dhana_yoga', 'arishta', 'neecha_bhanga', 'functional_dignity')."""
        pass

    @abstractmethod
    def evaluate(
        self,
        context: CalculationContext,
        engine_outputs: Optional[Dict[str, Any]] = None,
        varga_outputs: Optional[Dict[str, Any]] = None,
    ) -> RuleResult:
        """
        Evaluates rule condition against CalculationContext, Vedic Engine outputs, and Varga outputs.

        Args:
            context: Immutable CalculationContext envelope.
            engine_outputs: Optional output dict from VedicEngine.
            varga_outputs: Optional output dict from VargaRegistry.

        Returns:
            RuleResult entity.
        """
        pass


class IRuleEngine(ABC):
    """
    Abstract Base Class for Rule Engine dispatchers.
    """

    @abstractmethod
    def register_rule(self, rule: IRule) -> None:
        """Registers a new rule implementation."""
        pass

    @abstractmethod
    def evaluate_all(
        self,
        context: CalculationContext,
        engine_outputs: Optional[Dict[str, Any]] = None,
        varga_outputs: Optional[Dict[str, Any]] = None,
    ) -> List[RuleResult]:
        """Evaluates all registered rules in priority order."""
        pass
